### ISSUE TITLE
add vagrant-libvirt support?

### ISSUE THREAD

**Issue by hemna** [upperstream/packer-templates#147]
Would be useful to add vagrant libvirt support for building these images.

**Comment by upperstream** [comment]
Thank you for your suggestion.  Will make an effort to support libvirt.

**Comment by upperstream** [comment]
Templates for Alpine Linux 3.12.0 support Vagrant Libvirt provider.

**Comment by upperstream** [comment]
In order for Alpine Linux to support NFS as a QEMU guest, the following packages are required:

- `nfs-utils` for `rpc.statd(8)`
- `util-linux` for `sfdisk(8)`

**Comment by upperstream** [comment]
As of writing this, the following templates support libvirt provider:

* Alpine
* CentOS
* Debian
* Devuan
* FreeBSD
* NetBSD
* OpenBSD
